### find

GET http://localhost:8080/vehicle/23

### person find by id

GET http://localhost:8080/persons/1

### vehicle find by id

GET http://localhost:8080/vehicles/1

### find all vehicles

GET http://localhost:8080/vehicles

###